#Выводим Minio наружу чтобы могли к нему подключаться
service:
  type: NodePort
  ports:
    api: 9000
    console: 9001
  nodePorts:
    api: "32224"
    console: "32225"

#Указываем размер PVC под Minio
persistence:
  size: 8Gi

#Данные входа в Minio
auth:
  rootUser: mlflow
  rootPassword: "pomenya_parol"

#Бакет по умолчанию
defaultBuckets: "mlflow"