apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-conf-configmap
data:
  nginx.conf: |
    events {
    }
    http {
        server {
            listen 80;
            server_name mlflow;
            location / {
                auth_basic "Restricted Access";
                auth_basic_user_file /etc/nginx/.htpasswd;
                proxy_pass http://mlflow-server-service:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
        }
    }