apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mlflow-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{ .Release.Name }}-nginx-conf-configmap
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: {{ .Release.Name }}-nginx-auth-secret
              mountPath: /etc/nginx/.htpasswd
              readOnly: true
              subPath: .htpasswd
          env:
            - name: AUTH_BASIC_USER_FILE
              value: "/etc/nginx/.htpasswd"
      volumes:
        - name: {{ .Release.Name }}-nginx-conf-configmap
          configMap:
            name: {{ .Release.Name }}-nginx-conf-configmap
        - name: {{ .Release.Name }}-nginx-auth-secret
          secret:
            secretName: {{ .Release.Name }}-nginx-auth-secret