apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.mlflow.port }}
      targetPort: 80
      {{- if eq .Values.mlflow.serviceType "NodePort" }}
      nodePort: {{ .Values.mlflow.NodePort }}
      {{- end }}
  type: {{ .Values.mlflow.serviceType }}
