annotations:
  category: WorkFlow
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.6.1
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 17.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Airflow is a tool to express and execute workflows as directed
  acyclic graphs (DAGs). It includes utilities to schedule tasks, monitor task progress
  and handle task dependencies.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/airflow/img/airflow-stack-220x234.png
keywords:
- apache
- airflow
- workflow
- dag
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: airflow
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/airflow
version: 14.2.5
