apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G