apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-gitea-runner-cluster-role
rules:
- apiGroups: ["*"]
  resources:  ["pods","pods/log"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources:  ["services"]
  verbs: ["get", "list"]