apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-gitea-runner-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ .Values.ServiceAccount }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-gitea-runner-cluster-role
  apiGroup: rbac.authorization.k8s.io